---
:concurrency: 5
:pidfile: tmp/pids/sidekiq.pid
:logfile: ./log/sidekiq.log

development:
  :logfile: ./log/sidekiq_development.log
staging:
  :concurrency: 10
production:
  :concurrency: 20
:queues:
  - [critical, 2]
  - default
  - low